# Dockerfile.dev
FROM node:22-alpine3.19

# Set to development mode instead of production
ENV NODE_ENV=development

# Same dependencies as production
RUN apk --no-cache add python3 py3-pip \
    && python3 -m venv /venv \
    && /venv/bin/pip install --no-cache-dir pandas tabulate

ENV PATH="/venv/bin:$PATH"

WORKDIR /usr/src/app

COPY package*.json ./

# Install ALL dependencies (including dev)
RUN npm install

COPY . .

# Run in dev mode instead of production
CMD [ "npm", "run", "start:debug" ]